### ISSUE TITLE
Export a complete datapack is not possible

### ISSUE THREAD

**Issue by TaniDey** [Codeneos/vlocode#14]
It is possible to export single record but not possible to export a whole datapack. Did some changes in multiple product records and in vlocode and then I didn't got any option to export all the records at once.

**Comment by Codeneos** [comment]
Good suggestion, will incorporate an export all function in the next release.

**Comment by Codeneos** [comment]
Added support in version 0.10.5:

![image](https://user-images.githubusercontent.com/787686/59020272-efe0fb80-8849-11e9-913a-ea6430f3bfd5.png)
