### ISSUE TITLE
Unable to Refresh Datapacks

### ISSUE THREAD

**Issue by CheesecakeCat** [Codeneos/vlocode#153]
I've run into an odd problem while trying to use VSCode while working on Vlocity UI Templates. When trying to refresh a specific datapack, or the folder for UI templates, I get the following error in the terminal: 

[CommandExecutor] [error] Command error: Object type VlocityUITemplate does not have a matching key specified in Salesforce.

Oddly enough, the vlocity extension is partially working. I can export datapacks from the vlocity panel, and I can deploy datapacks from my workspace into the org without an issue. The problem appears to be with just refreshing datapacks. 

I've tried making a brand new workspace, and re-authorizing an org, but the error still happens. 

I've attached a screenshot of what my terminal looked like after trying to refresh 2 different datapacks, and then successfully exporting the same datapack from the Datapacks panel.

![vlocity extension refreshing datapacks error](https://user-images.githubusercontent.com/43553336/75051084-de508a00-5492-11ea-9db1-87d15bd628fd.png)

**Comment by thisguyjacob** [comment]
Facing same issue as **Unable to Refresh Datapacks** #153

**Comment by Codeneos** [comment]
Thanks for reporting the problem! Apologies for the late reply; somehow I didn't see the github issue notice :(.

The problem should now be be fixed; can you test this on version 0.12.14 and let me know if you are still facing the same issue.
