### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zleroy** [Codeneos/vlocode#360]
- Issue Type: `Performance`
- Extension Name: `vlocode`
- Extension Version: `0.16.6`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.59.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\spgztl\AppData\Local\Temp\curlybracket.vlocode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Codeneos** [comment]
Can you attach a log file to this?

**Comment by Codeneos** [comment]
Closing issue as no reply or log was received.
