### ISSUE TITLE
Extention doesn't start properly on version > 0.16.12

### ISSUE THREAD

**Issue by TomaszWr** [Codeneos/vlocode#362]
I am not able to upgrade plugin above the version in the subject. When I do, the plugin seems to be not enabled and when I am trying to run any command, like connect to org, I got issues something like "cannot run vlocode.selectorg". 

I run vscode on macOS with bunch of other SF-related extensions. Anyone else has such issue and managed to fix it?

**Comment by Codeneos** [comment]
I noticed that there is an issue with the build and webpack is trying to embedded mocha as dependency whereas mocha should only be there for unit tests.

![image](https://user-images.githubusercontent.com/787686/140657582-a353d173-92ab-4cd3-a701-8abc35e19c8d.png)

I'll have to investigate this further and will release a manually build of the 0.16.15 that should fix it.

**Comment by Codeneos** [comment]
@TomaszWr found the issue and pushed an update; it is going to be released as v0.16.16. Hopefully this will fix the issue.

**Comment by TomaszWr** [comment]
Thanks this particular issue has been fixed for me. But I am receiving new one, sadly... Will raise as other ticket.
