### ISSUE TITLE
Contextual omniscript datapack refresh is failing with query error

### ISSUE THREAD

**Issue by TomaszWr** [Codeneos/vlocode#365]
After selecting  omniscript from explorer I am getting some errors, please check the file attached
[log.txt](https://github.com/Codeneos/vlocode/files/7504063/log.txt)

First part of an error is, I think, one time error - following shows up each time I refresh:
```
[error] Query Error 
vlocity_cmt__OmniScript__c WHERE  ORDER BY LastModifiedDate DESC LIMIT
                                       ^
ERROR at Row:1:Column:55
unexpected token: 'BY'
```

Datapacks can be exported by the vlocity datapack tab.

**Comment by Codeneos** [comment]
Thanks for the bug! I noticed this as well and it is now fixed in version 0.16.17

**Comment by Codeneos** [comment]
0.16.17 should be available now and should have addressed the issue.

@TomaszWr once again thanks for reporting the issue! 👍

**Comment by TomaszWr** [comment]
Thank you for fixing! Work perfectly now. :)
