### ISSUE TITLE
Error using Export Datapack from Org command

### ISSUE THREAD

**Issue by pchang96** [Codeneos/vlocode#379]
I am suddenly encountering this error after using the Export Datapack from Org command and selecting OmniScript/OmniScriptVersion, IntegrationProcedure/IntegrationProcedureVersion, and VlocityCards. I do not get this error when selecting DataRaptor, CalculationMatrix, or CalculationProcedure. From the Terminal logs:

`[CommandExecutor] [error] Command error: 'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property '$$result' that is incompatible with the existing property in the proxy target`

Clicking the dropdown in the Vlocity datapack tab throws the same error.
Edit: I am not certain if this is an issue with VSCode, the extension, or the Salesforce org itself.

**Comment by siriusSpa** [comment]
I have the same error too.
I think the error started when VS Code updated to 1.67.0 version.

**Comment by Codeneos** [comment]
Jup, seems to be related to a NodeJS version increase that happened with the VS COde update to 1.67.0 - I updated the affected component and will push a fix in 0.16.22

**Comment by pchang96** [comment]
Installed version 0.16.22 and export works fine now. Thanks for the quick response!
