### ISSUE TITLE
Command error: (intermediate value).find is not a function Salesforce Vlocity Integration (Extension) Error

### ISSUE THREAD

**Issue by krishnan-iyer** [Codeneos/vlocode#380]
Observed this recently after updates to Salesforce Vlocity Integration (Extension) & sfdx. Reverting to older version does not fix the issue so the issue may be related to something other than the update.

Receiving the following error on performing any action related to the Vlocity Integration extension (for eg: Vlocity: Deploy Datapack to Org). Salesforce deploy to the same authorised org works fine.

Command error: (intermediate value).find is not a function

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/87111193/168633294-f7273393-9368-4544-bed5-9e2c8e909a68.png">

Troubleshooting tried so far:
1) Downgraded the Salesforce Vlocity Integration (Extension) to v0.16.18 & v0.16.16.
2) Tried with node version 12.xx & 14.xx
3) Uninstalled & Reinstalled the extension after restarting VS code between every step
4) sfdx-cli is updated to the latest version as is the Salesforce Extension Pack. (v54.12.0)

**Comment by Codeneos** [comment]
Thanks for reporting this. The extension uses the NodeJS version bundle with VSCode and bundles it's own version of the SFDX to NodeJS package avoid any compatibility issues.

Can you provide me with a debug log with stack trace? It should be available when clicking through the debug console integrated into vscode, you can reach it by clicking on `Help > Toggle Developer Tools`.

**Comment by krishnan-iyer** [comment]
Thank you for your prompt response. Attaching the console log herewith. Here's a screenshot just in case.

My VS Code version info: 
Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

<img width="552" alt="image" src="https://user-images.githubusercontent.com/87111193/168824738-e5347393-00a3-483a-8b84-3819266eee46.png">
[vscode-app-1652794636192.log](https://github.com/Codeneos/vlocode/files/8708740/vscode-app-1652794636192.log)

**Comment by Codeneos** [comment]
Thanks! The log is helpful 👍  

I'll try to reproduce the issue tomorrow a few different org

**Comment by Codeneos** [comment]
@krishnan-iyer Hey 👋, I think I finally found the root cause of this issue.

It was a bit chucked away but I think it has to do with package detection code that uses the tooling API to query for installed packages on the target org.  I pushed a potentional fix today and aim to push out a new release of the extension later this week.

**Comment by krishnan-iyer** [comment]
@Codeneos Thank you for persisting on this. Will await the next release.

**Comment by Codeneos** [comment]
I did some fixes in 0.18.x release can you give it a go and let me know if that works?

**Comment by shishirbansal** [comment]
Hi, 

OS : MAC (12.6.1) Monterey
SF cli : sfdx-cli/7.180.0 darwin-x64 node-v18.12.1
Vs Code Version :  1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0

Recently i am not able to use the Vlocity VScode  extension. I tried to uninstall the extension and salesforce one and then VS code also. Reinstalled everything from scratch and able to work with Salesforce extension but not able to connect the org for vlocity. Even cleaned the alias and logged out from all the orgs in terminal and started with just one org but no luck. I am attaching the screenshot. Please let me know if there is something that is missing from my end or if this is the known issue. 
<img width="1300" alt="Screenshot 2022-12-15 at 8 23 38 AM" src="https://user-images.githubusercontent.com/23053736/207761435-1f905892-2dc8-48e5-a324-7634cdadfe1d.png">
