### ISSUE TITLE
False "Could not connect to Salesforce"

### ISSUE THREAD

**Issue by omgitscurii** [Codeneos/vlocode#387]
Hi,

I'm using Vlocode v0.17.9 and although it is connected to a Salesforce org and fully functional, it still displays "Could no connect to Salesforce". The only error I see in the console is: "**[error] SObject Attachment is not acessible by the current user**"

**Comment by Codeneos** [comment]
That's strange. I've never seen that error before. Just to be sure you do have the permissions set on profile to access Attachments?

Could you send me a debug log? You can set the log level to debug from the extension settings.

**Comment by omgitscurii** [comment]
Hi,

Yes, I'm connected with a user with Profile "System Administrator". I can access SObject "Attachment".

Attaching log.
[debug_log_COULD-NOT-CONNECT-TO-SALESFORCE.txt](https://github.com/Codeneos/vlocode/files/9733335/debug_log_COULD-NOT-CONNECT-TO-SALESFORCE.txt)

**Comment by Codeneos** [comment]
Thanks for the log! I tried to reproduce it myself but couldn't. I’ll be
doing some more tests over the next few days but might need some additional
help from you in order to fix this issue.

I’ll keep you posted.

**Comment by Codeneos** [comment]
@omgitscurii I have my suspicions as to what is causing the issue; I created a test version. Could you validate this version resolves the issue? It should also print a more detailed error in log.

Could you try to test if you can reproduce the issue with this version? You can simply extract the VISX package from the zip file and install it manually from the Extensions panel from "Install from VSIX..."

![image](https://user-images.githubusercontent.com/787686/194940950-bbb2cc5c-a1d9-4572-b8da-8f16f8753dc8.png)

[vlocode-0.17.10-beta.vsix.zip](https://github.com/Codeneos/vlocode/files/9748511/vlocode-0.17.10-beta.vsix.zip)

**Comment by Codeneos** [comment]
Thanks for the verification 👍

I'll be releasing an updated version of the extension with the fix  as version 0.17.11

**Comment by omgitscurii** [comment]
Thank you for the prompt response.
