### ISSUE TITLE
Unable to initialize Vlocode on vscode

### ISSUE THREAD

**Issue by ShreyasD** [Codeneos/vlocode#397]
Getting the following error when trying to initialize Vlocode plugin in vscode. 

**Vscode Info**
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

**Comment by a470836-abloomfield** [comment]
did you look at issue #395 ?

**Comment by Codeneos** [comment]
@ShreyasD as suggested by @a470836-abloomfield I will need some extra details to understand the root cause. You can get more details and a stacktrace from the developer logs from vscode which can be enabled through the `Help > Toggle Developer Console` item.

**Comment by Codeneos** [comment]
Closing this issue 0.19.x branch will hopefully have fixed this issue
