### ISSUE TITLE
Command error: Vlocode is not initialized; VlocityDatapackService is null

### ISSUE THREAD

**Issue by shishirbansal** [Codeneos/vlocode#401]
This is related to previous issue. My apologise, i don't have any intention of spamming.

https://github.com/Codeneos/vlocode/issues/395#issuecomment-1520402410

**Comment by Codeneos** [comment]
Hey @shishirbansal - please the details about the error into this issue instead of in the previous one that way it is easier for me to track as I don't think this is related to the previous issue.

**Comment by shishirbansal** [comment]
Ok , I have reinstalled **Salesforce Vlocity Integration**. extension on the VsCode plus i have updated the Java setting, along with sfdx update. Everything is working fine just that from the vlocode extension i am not able to select the alias or the users org. here are the screenshots attached
below is the sfdx extension 
<img width="1440" alt="Screenshot 2023-05-22 at 10 18 40 AM" src="https://github.com/Codeneos/vlocode/assets/23053736/b6ffd5b0-4253-4ee0-a7c0-e065d678cefc">

![Uploading Screenshot 2023-05-22 at 10.18.35 AM.png…]()
above one not able to authorise or connect to any org

**Comment by Codeneos** [comment]
@shishirbansal this issue should be addressed. Can you let me know if it is fixed?

**Comment by shishirbansal** [comment]
Hello @Codeneos , Thanks for the help and support. the issue is resolved
