### ISSUE TITLE
Support for Device Code Login

### ISSUE THREAD

**Issue by Clint-Chester** [Codeneos/vlocode#415]
Hey there 😄 was wondering if it would be possible to be able to get support using the device login capability - https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_org_commands_unified.htm#cli_reference_org_login_device_unified

Reason for the request is that it will help people using Dev Containers like [GitHub Codespaces](https://github.com/features/codespaces), [Gitpod](https://www.gitpod.io/) and [Coder](https://coder.com/).

Checking out the SF CLI, this was how they were managing auth with devices - https://github.com/salesforcecli/plugin-auth/blob/3.0.8/src/commands/org/login/device.ts

Would this be possible? Happy to help if you've got any pointers on what would be needed to update to support Device Login.

**Comment by Codeneos** [comment]
Hey :) Yes, that should definitely be possible. I just went through the docs and this should be a minor addition. 

I haven't used the device flow myself but looking at the code and documentation I think shouldn't take long to add this.

**Comment by Codeneos** [comment]
@Clint-Chester version `0.20.10` has support for device flow login. It should be available from the market place soon.

When authorizing a new org you can chose `Device Login Flow` which will start the device code flow:

![image](https://github.com/Codeneos/vlocode/assets/787686/fdddd1e6-4091-4215-be8e-ff99d5fa8e4c)

And thanks for linking the code in the auth plugin from `sf`, that was quite useful!

Let me know if this helps. 

And if additional changes are needed to properly support DevContainer's let me know.
